// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CategoryComp: typeof import('./src/components/CategoryComp.vue')['default']
    CommentList: typeof import('./src/components/CommentList.vue')['default']
    CommentView: typeof import('./src/components/CommentView.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MainView: typeof import('./src/components/MainView.vue')['default']
    NavView: typeof import('./src/components/NavView.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RankView: typeof import('./src/components/RankView.vue')['default']
    Recommend: typeof import('./src/components/Recommend.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchView: typeof import('./src/components/SearchView.vue')['default']
    SwiperView: typeof import('./src/components/SwiperView.vue')['default']
    UpdateComp: typeof import('./src/components/UpdateComp.vue')['default']
    UploadComp: typeof import('./src/components/UploadComp.vue')['default']
    UploadVideo: typeof import('./src/components/UploadVideo.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
    UserView: typeof import('./src/components/UserView.vue')['default']
    VideoContent: typeof import('./src/components/VideoContent.vue')['default']
    VideoList: typeof import('./src/components/VideoList.vue')['default']
    VideoPlayer: typeof import('./src/components/VideoPlayer.vue')['default']
    VideoView: typeof import('./src/components/VideoView.vue')['default']
  }
}
